version: '3.8'

services:
  app:
    build: .
    ports:
      - "32776:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - NODE_ENV=production
    restart: always
